version: '3'
services:
  front:
    build: ./front
    container_name: front
    tty: true
    ports:
      - 3000:3000
    stdin_open: true
    # プロジェクトディレクトリにマウントする
    volumes:
      - ./front/legacyvault:/app/legacyvault
    working_dir: /app/legacyvault
    environment:
      - WATCHPACK_POLLING=true
    command: sh -c "npm i && npm run dev"
    networks:
      - lesson
  back:
    build:
      context: ./back
      dockerfile: Dockerfile
    container_name: back
    ports:
      - 1323:1323
    tty: true
    restart: always
    volumes:
      - ./back/src:/go/src
    working_dir: /go/src
    # command: air -c .air.toml
    networks:
      - lesson
  postgres:
    build:
      context: ./postgres
      dockerfile: Dockerfile
    container_name: postgres
    volumes:
      - ./postgres/init:/docker-entrypoint-initdb.d
    ports:
      - 5433:5432
    restart: always
    networks:
      - lesson
networks:
  lesson: